name: zippy
description: "Mobile application for smart delivery with AI robot"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.5.3+2
  flutter_dotenv: ^5.2.1
  flutter:
    sdk: flutter  

  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  provider: ^6.1.5
  easy_localization: ^3.0.3
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  lucide_icons: ^0.257.0
  jwt_decoder: ^2.0.1
  flutter_phoenix: ^1.1.0
  
  # Map and location services
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  location: ^5.0.0
  geocoding: ^2.2.0
  http_auth: ^1.0.2
  crypto: ^3.0.3
  convert: ^3.1.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mobile_scanner: ^5.2.3
  pin_code_fields: ^8.0.1
  mqtt_client: ^10.2.0
  flutter_local_notifications: ^17.2.2
  workmanager: ^0.9.0+2
  webview_flutter: ^4.4.4
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png" # Make sure logo.png is 512x512 with extra padding
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"
    theme_color: "#2196F3"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true
  # The logo should have extra white space/padding in the PNG itself to reduce its visible size

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/en-US.json
    - assets/translations/vi-VN.json
    - .env

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300