name: zippy
description: "Mobile application for smart delivery with AI robot"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.5.3+2
  flutter_dotenv: ^5.2.1
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^6.1.5
  easy_localization: ^3.0.3
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  lucide_icons: ^0.257.0
  
  # Map and location services
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  location: ^5.0.0
  geocoding: ^2.2.0
  
  # AWS Services
  amazon_cognito_identity_dart_2: ^3.6.0
  http_auth: ^1.0.2
  crypto: ^3.0.3
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/en-US.json
    - assets/translations/vi-VN.json
    - .env

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300